{
    "active_lock_reason": null,
    "assignee": null,
    "assignees": [],
    "author_association": "NONE",
    "body": "### Problem\n\nLooks like there may be a bug in NVims Python emulation layer. \r\n\r\n```text\r\nError executing vim.schedule lua callback: function cmp_nvim_ultisnips#get_current_snippets[33]..provider#python3#Call, line 18: Vim(return):Error invoking 'python\r\n_execute' on channel 8 (python3-script-host):                                                                                                                      \r\nTraceback (most recent call last):                                                                                                                                 \r\n  File \"<string>\", line 22, in <module>                                                                                                                            \r\n  File \"/usr/lib/python3.12/site-packages/pynvim/api/nvim.py\", line 287, in command                                                                                \r\n    return self.request('nvim_command', string, **kwargs)                                                                                                          \r\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                          \r\n  File \"/usr/lib/python3.12/site-packages/pynvim/api/nvim.py\", line 182, in request                                                                                \r\n    res = self._session.request(name, *args, **kwargs)                                                                                                             \r\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                             \r\n  File \"/usr/lib/python3.12/site-packages/pynvim/msgpack_rpc/session.py\", line 102, in request                                                                     \r\n    raise self.error_wrapper(err)                                                                                                                                  \r\npynvim.api.common.NvimError: Vim:<action-code>:1: SyntaxWarning: invalid escape sequence '\\e'                                                                      \r\nstack traceback:                                                                                                                                                   \r\n        [C]: in function 'load_snippets'                                                                                                                           \r\n        ...ged/cmp-nvim-ultisnips/lua/cmp_nvim_ultisnips/source.lua:27: in function 'complete'                                                                     \r\n        ...ritchie/.config/nvim/plugged/nvim-cmp/lua/cmp/source.lua:334: in function 'complete'                                                                    \r\n        ...e/ritchie/.config/nvim/plugged/nvim-cmp/lua/cmp/core.lua:299: in function 'complete'                                                                    \r\n        ...e/ritchie/.config/nvim/plugged/nvim-cmp/lua/cmp/core.lua:169: in function 'autoindent'                                                                  \r\n        ...e/ritchie/.config/nvim/plugged/nvim-cmp/lua/cmp/core.lua:161: in function 'on_change'                                                                   \r\n        ...e/ritchie/.config/nvim/plugged/nvim-cmp/lua/cmp/init.lua:338: in function 'callback'                                                                    \r\n        ...ie/.config/nvim/plugged/nvim-cmp/lua/cmp/utils/async.lua:165: in function <...ie/.config/nvim/plugged/nvim-cmp/lua/cmp/utils/async.lua:163>  \r\n```\n\n### Steps to reproduce\n\nIt randomly happens when I try to open a file with `:vs` to open another file with tab.\n\n### Expected behavior\n\nNo errors.\n\n### Neovim version (nvim -v)\n\nNVIM v0.9.4\n\n### Vim (not Nvim) behaves the same?\n\nno\n\n### Operating system/version\n\nLinux void 6.5.13_1 #1 SMP PREEMPT_DYNAMIC Thu Nov 30 23:19:06 UTC 2023 x86_64 GNU/Linux\n\n### Terminal name/version\n\nkitty 0.31.0 created by Kovid Goyal\n\n### $TERM environment variable\n\nxterm-kitty\n\n### Installation\n\nxbps-install -S neovim",
    "closed_at": "2023-12-04T04:14:30Z",
    "comment_data": [
        {
            "author_association": "CONTRIBUTOR",
            "body": "Please provide specific reproducible steps. The '\\e' character probably comes from a snippet file in your config, so you may want to take a look at those snippet files. This is likely to be a plugin error (https://github.com/quangnguyen30192/cmp-nvim-ultisnips), not neovim core (or pynvim's error): `cmp_nvim_ultisnips#get_current_snippets`",
            "created_at": "2023-12-04T04:07:49Z",
            "html_url": "https://github.com/neovim/neovim/issues/26377#issuecomment-1837807608",
            "id": 1837807608,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/26377",
            "node_id": "IC_kwDOAPphoM5tirf4",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1837807608/reactions"
            },
            "updated_at": "2023-12-04T04:10:43Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/1837807608",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/1009873?v=4",
                "events_url": "https://api.github.com/users/wookayin/events{/privacy}",
                "followers_url": "https://api.github.com/users/wookayin/followers",
                "following_url": "https://api.github.com/users/wookayin/following{/other_user}",
                "gists_url": "https://api.github.com/users/wookayin/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/wookayin",
                "id": 1009873,
                "login": "wookayin",
                "node_id": "MDQ6VXNlcjEwMDk4NzM=",
                "organizations_url": "https://api.github.com/users/wookayin/orgs",
                "received_events_url": "https://api.github.com/users/wookayin/received_events",
                "repos_url": "https://api.github.com/users/wookayin/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/wookayin/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/wookayin/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/wookayin"
            }
        }
    ],
    "comments": 1,
    "comments_url": "https://api.github.com/repos/neovim/neovim/issues/26377/comments",
    "created_at": "2023-12-04T03:43:48Z",
    "events_url": "https://api.github.com/repos/neovim/neovim/issues/26377/events",
    "html_url": "https://github.com/neovim/neovim/issues/26377",
    "id": 2022957589,
    "labels": [
        {
            "color": "e6e6e6",
            "default": false,
            "description": "Issues that are closed as \"invalid\"",
            "id": 77997477,
            "name": "closed:invalid",
            "node_id": "MDU6TGFiZWw3Nzk5NzQ3Nw==",
            "url": "https://api.github.com/repos/neovim/neovim/labels/closed:invalid"
        }
    ],
    "labels_url": "https://api.github.com/repos/neovim/neovim/issues/26377/labels{/name}",
    "locked": false,
    "milestone": null,
    "node_id": "I_kwDOAPphoM54k-IV",
    "number": 26377,
    "performed_via_github_app": null,
    "reactions": {
        "+1": 0,
        "-1": 0,
        "confused": 0,
        "eyes": 0,
        "heart": 0,
        "hooray": 0,
        "laugh": 0,
        "rocket": 0,
        "total_count": 0,
        "url": "https://api.github.com/repos/neovim/neovim/issues/26377/reactions"
    },
    "repository_url": "https://api.github.com/repos/neovim/neovim",
    "state": "closed",
    "state_reason": "not_planned",
    "timeline_url": "https://api.github.com/repos/neovim/neovim/issues/26377/timeline",
    "title": "pynvim.api.common.NvimError: Vim:<action-code>:1: SyntaxWarning: invalid escape sequence '\\e'      ",
    "updated_at": "2023-12-04T04:14:40Z",
    "url": "https://api.github.com/repos/neovim/neovim/issues/26377",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/76216665?v=4",
        "events_url": "https://api.github.com/users/rickalex21/events{/privacy}",
        "followers_url": "https://api.github.com/users/rickalex21/followers",
        "following_url": "https://api.github.com/users/rickalex21/following{/other_user}",
        "gists_url": "https://api.github.com/users/rickalex21/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/rickalex21",
        "id": 76216665,
        "login": "rickalex21",
        "node_id": "MDQ6VXNlcjc2MjE2NjY1",
        "organizations_url": "https://api.github.com/users/rickalex21/orgs",
        "received_events_url": "https://api.github.com/users/rickalex21/received_events",
        "repos_url": "https://api.github.com/users/rickalex21/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/rickalex21/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/rickalex21/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/rickalex21"
    }
}