{
    "active_lock_reason": null,
    "assignee": null,
    "assignees": [],
    "author_association": "NONE",
    "body": "### Problem\n\nThis error appears when trying to use shift + k on a module in a Python file while having Python 3.13.x installed:\n\n```\nCould not import runpy module\nTraceback (most recent call last):\n  File \"<frozen importlib._bootstrap>\", line 1360, in _find_and_load\n  File \"<frozen importlib._bootstrap>\", line 1331, in _find_and_load_unlocked\n  File \"<frozen importlib._bootstrap>\", line 935, in _load_unlocked\n  File \"<frozen importlib._bootstrap>\", line 1176, in exec_module\n  File \"<frozen runpy>\", line 15, in <module>\n  File \"<frozen importlib._bootstrap>\", line 1360, in _find_and_load\n    File \"<frozen importlib._bootstrap>\", line 1331, in _find_and_load_unlocked\n    File \"<frozen importlib._bootstrap>\", line 935, in _load_unlocked\n    File \"<frozen importlib._bootstrap>\", line 1176, in exec_module\n    File \"<frozen importlib.util>\", line 16, in <module>\n    File \"D:\\Programme\\Python\\Lib\\threading.py\", line 35, in <module>\n      _start_joinable_thread = _thread.start_joinable_thread\n                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n AttributeError: module '_thread' has no attribute 'start_joinable_thread'\n```\n\n\n\n\n\n### Steps to reproduce\n\n- nvim file.py\n- import a python library (in my example `import shutil`)\n- select `shutil`\n- shift+k\n\n### Expected behavior\n\nkeyword lookup works fine when Python 3.12.x is installed:\n\n![Image](https://github.com/user-attachments/assets/4226163c-6bd8-4444-8383-11dc303203c3)\n\nSetting keywordprg to `python -m pydoc` instead of `python3 -m pydoc` might be a quick fix\n\n![Image](https://github.com/user-attachments/assets/8890de6f-f5b2-4f5f-af51-59d291722d10)\n\n\n### Nvim version (nvim -v)\n\nNVIM v0.10.3\n\n### Vim (not Nvim) behaves the same?\n\nyes, vim 9.1\n\n### Operating system/version\n\nWindows 11 24H2\n\n### Terminal name/version\n\nWindows Terminal V1.21.3231.0\n\n### $TERM environment variable\n\n(not set)\n\n### Installation\n\nchocolatey",
    "closed_at": "2024-12-25T23:59:32Z",
    "closed_by": {
        "avatar_url": "https://avatars.githubusercontent.com/u/35768171?v=4",
        "events_url": "https://api.github.com/users/zeertzjq/events{/privacy}",
        "followers_url": "https://api.github.com/users/zeertzjq/followers",
        "following_url": "https://api.github.com/users/zeertzjq/following{/other_user}",
        "gists_url": "https://api.github.com/users/zeertzjq/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/zeertzjq",
        "id": 35768171,
        "login": "zeertzjq",
        "node_id": "MDQ6VXNlcjM1NzY4MTcx",
        "organizations_url": "https://api.github.com/users/zeertzjq/orgs",
        "received_events_url": "https://api.github.com/users/zeertzjq/received_events",
        "repos_url": "https://api.github.com/users/zeertzjq/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/zeertzjq/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/zeertzjq/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/zeertzjq",
        "user_view_type": "public"
    },
    "comment_data": [
        {
            "author_association": "MEMBER",
            "body": "Since this happens when you run `python3 -m pydoc` on the command line as well, this is a problem with your environment.",
            "created_at": "2024-12-25T23:59:32Z",
            "html_url": "https://github.com/neovim/neovim/issues/31728#issuecomment-2562028071",
            "id": 2562028071,
            "issue_url": "https://api.github.com/repos/neovim/neovim/issues/31728",
            "node_id": "IC_kwDOAPphoM6YtXIn",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/neovim/issues/comments/2562028071/reactions"
            },
            "updated_at": "2024-12-26T00:05:29Z",
            "url": "https://api.github.com/repos/neovim/neovim/issues/comments/2562028071",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/35768171?v=4",
                "events_url": "https://api.github.com/users/zeertzjq/events{/privacy}",
                "followers_url": "https://api.github.com/users/zeertzjq/followers",
                "following_url": "https://api.github.com/users/zeertzjq/following{/other_user}",
                "gists_url": "https://api.github.com/users/zeertzjq/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/zeertzjq",
                "id": 35768171,
                "login": "zeertzjq",
                "node_id": "MDQ6VXNlcjM1NzY4MTcx",
                "organizations_url": "https://api.github.com/users/zeertzjq/orgs",
                "received_events_url": "https://api.github.com/users/zeertzjq/received_events",
                "repos_url": "https://api.github.com/users/zeertzjq/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/zeertzjq/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/zeertzjq/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/zeertzjq",
                "user_view_type": "public"
            }
        }
    ],
    "comments": 1,
    "comments_url": "https://api.github.com/repos/neovim/neovim/issues/31728/comments",
    "created_at": "2024-12-25T22:47:41Z",
    "events_url": "https://api.github.com/repos/neovim/neovim/issues/31728/events",
    "html_url": "https://github.com/neovim/neovim/issues/31728",
    "id": 2759113816,
    "labels": [
        {
            "color": "e6e6e6",
            "default": false,
            "description": "Issues that are closed as \"invalid\"",
            "id": 77997477,
            "name": "closed:invalid",
            "node_id": "MDU6TGFiZWw3Nzk5NzQ3Nw==",
            "url": "https://api.github.com/repos/neovim/neovim/labels/closed:invalid"
        }
    ],
    "labels_url": "https://api.github.com/repos/neovim/neovim/issues/31728/labels{/name}",
    "locked": false,
    "milestone": null,
    "node_id": "I_kwDOAPphoM6kdLxY",
    "number": 31728,
    "performed_via_github_app": null,
    "reactions": {
        "+1": 0,
        "-1": 0,
        "confused": 0,
        "eyes": 0,
        "heart": 0,
        "hooray": 0,
        "laugh": 0,
        "rocket": 0,
        "total_count": 0,
        "url": "https://api.github.com/repos/neovim/neovim/issues/31728/reactions"
    },
    "repository_url": "https://api.github.com/repos/neovim/neovim",
    "state": "closed",
    "state_reason": "not_planned",
    "sub_issues_summary": {
        "completed": 0,
        "percent_completed": 0,
        "total": 0
    },
    "timeline_url": "https://api.github.com/repos/neovim/neovim/issues/31728/timeline",
    "title": "Can't import runpy error when trying to do a keyword lookup on a module in Python",
    "updated_at": "2024-12-26T00:05:29Z",
    "url": "https://api.github.com/repos/neovim/neovim/issues/31728",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/139477516?v=4",
        "events_url": "https://api.github.com/users/FranzMartyn/events{/privacy}",
        "followers_url": "https://api.github.com/users/FranzMartyn/followers",
        "following_url": "https://api.github.com/users/FranzMartyn/following{/other_user}",
        "gists_url": "https://api.github.com/users/FranzMartyn/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/FranzMartyn",
        "id": 139477516,
        "login": "FranzMartyn",
        "node_id": "U_kgDOCFBCDA",
        "organizations_url": "https://api.github.com/users/FranzMartyn/orgs",
        "received_events_url": "https://api.github.com/users/FranzMartyn/received_events",
        "repos_url": "https://api.github.com/users/FranzMartyn/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/FranzMartyn/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/FranzMartyn/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/FranzMartyn",
        "user_view_type": "public"
    }
}