{
    "active_lock_reason": null,
    "assignee": null,
    "assignees": [],
    "author_association": "NONE",
    "body": "I am seeing a weird issue, where a function defined using `@plugin.function` does not get loaded *most* of the time.\r\n\r\nI have a python3 plugin called prj.py. I am defining a very simple function inside the plugin like this.\r\n```\r\n@pynvim.plugin\r\nclass Main(object):\r\n    ....\r\n    @pynvim.function('PJumpDef')\r\n    def PJumpDef(self, args):\r\n        logger.info('jump')\r\n        logger.info(args)\r\n```\r\nI run the `:UpdateRemotePlugins` command to generate remote plugin manifest. Now, if I restart nvim and try to execute the function using `:call PJumpDef()`, it fails to find the function. But, If I keep restarting nvim it works once in a while (but very rarely). \r\n\r\nThis function is also not available in the output of `:func` command.\r\n\r\nHowever,\r\nBy trial and error, I found that creating an `autocmd` like this in a prj.vim plugin file, I can get the function to load 100% of time.\r\n\r\n```\r\nautocmd VimEnter * call PJumpDef()\r\n```\r\n\r\nI know, this sounds very random and weird behavior, but this is bugging me for a while. Please let me know if there is some known fix for this.",
    "closed_at": "2023-12-05T00:02:08Z",
    "comment_data": [
        {
            "author_association": "NONE",
            "body": "I can call my functions, at the first time there is no tab auto-completion, but after called once, there is auto-completion.\r\nAlso, function does not accept named params.",
            "created_at": "2021-09-12T00:06:04Z",
            "html_url": "https://github.com/neovim/pynvim/issues/386#issuecomment-917507153",
            "id": 917507153,
            "issue_url": "https://api.github.com/repos/neovim/pynvim/issues/386",
            "node_id": "IC_kwDOASpKTs42sAxR",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/917507153/reactions"
            },
            "updated_at": "2021-09-12T00:06:04Z",
            "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/917507153",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/2999805?v=4",
                "events_url": "https://api.github.com/users/thinker3/events{/privacy}",
                "followers_url": "https://api.github.com/users/thinker3/followers",
                "following_url": "https://api.github.com/users/thinker3/following{/other_user}",
                "gists_url": "https://api.github.com/users/thinker3/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/thinker3",
                "id": 2999805,
                "login": "thinker3",
                "node_id": "MDQ6VXNlcjI5OTk4MDU=",
                "organizations_url": "https://api.github.com/users/thinker3/orgs",
                "received_events_url": "https://api.github.com/users/thinker3/received_events",
                "repos_url": "https://api.github.com/users/thinker3/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/thinker3/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/thinker3/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/thinker3"
            }
        },
        {
            "author_association": "NONE",
            "body": "I am trying to resurect this thread, i am facing the same issue, if i call a python plugin method the first time it fails to return a valid value iget vim.NIL as a value if i call it second time (same args) then it returns a proper value . Note that the function itself seems to execute but the return value is not correct the first time you call it. Calling Update remote plugins does not seem to help",
            "created_at": "2022-03-30T14:03:12Z",
            "html_url": "https://github.com/neovim/pynvim/issues/386#issuecomment-1083180835",
            "id": 1083180835,
            "issue_url": "https://api.github.com/repos/neovim/pynvim/issues/386",
            "node_id": "IC_kwDOASpKTs5AkAcj",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1083180835/reactions"
            },
            "updated_at": "2022-03-30T14:03:12Z",
            "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1083180835",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/15955811?v=4",
                "events_url": "https://api.github.com/users/asmodeus812/events{/privacy}",
                "followers_url": "https://api.github.com/users/asmodeus812/followers",
                "following_url": "https://api.github.com/users/asmodeus812/following{/other_user}",
                "gists_url": "https://api.github.com/users/asmodeus812/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/asmodeus812",
                "id": 15955811,
                "login": "asmodeus812",
                "node_id": "MDQ6VXNlcjE1OTU1ODEx",
                "organizations_url": "https://api.github.com/users/asmodeus812/orgs",
                "received_events_url": "https://api.github.com/users/asmodeus812/received_events",
                "repos_url": "https://api.github.com/users/asmodeus812/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/asmodeus812/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/asmodeus812/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/asmodeus812"
            }
        },
        {
            "author_association": "NONE",
            "body": "I just experienced the issue described by @asmodeus812 and narrowed it down to an issue which is already fixed in https://github.com/neovim/pynvim/pull/496. In my case the issue still exists because the latest release, which is distributed in Arch, doesn't include it.",
            "created_at": "2022-11-12T17:56:09Z",
            "html_url": "https://github.com/neovim/pynvim/issues/386#issuecomment-1312538721",
            "id": 1312538721,
            "issue_url": "https://api.github.com/repos/neovim/pynvim/issues/386",
            "node_id": "IC_kwDOASpKTs5OO8Bh",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1312538721/reactions"
            },
            "updated_at": "2022-11-12T17:56:09Z",
            "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1312538721",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/4567628?v=4",
                "events_url": "https://api.github.com/users/notEvil/events{/privacy}",
                "followers_url": "https://api.github.com/users/notEvil/followers",
                "following_url": "https://api.github.com/users/notEvil/following{/other_user}",
                "gists_url": "https://api.github.com/users/notEvil/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/notEvil",
                "id": 4567628,
                "login": "notEvil",
                "node_id": "MDQ6VXNlcjQ1Njc2Mjg=",
                "organizations_url": "https://api.github.com/users/notEvil/orgs",
                "received_events_url": "https://api.github.com/users/notEvil/received_events",
                "repos_url": "https://api.github.com/users/notEvil/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/notEvil/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/notEvil/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/notEvil"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "Released 0.5: https://github.com/neovim/pynvim/releases/tag/0.5.0",
            "created_at": "2023-12-05T00:02:08Z",
            "html_url": "https://github.com/neovim/pynvim/issues/386#issuecomment-1839770298",
            "id": 1839770298,
            "issue_url": "https://api.github.com/repos/neovim/pynvim/issues/386",
            "node_id": "IC_kwDOASpKTs5tqKq6",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1839770298/reactions"
            },
            "updated_at": "2023-12-05T00:02:08Z",
            "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1839770298",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/1359421?v=4",
                "events_url": "https://api.github.com/users/justinmk/events{/privacy}",
                "followers_url": "https://api.github.com/users/justinmk/followers",
                "following_url": "https://api.github.com/users/justinmk/following{/other_user}",
                "gists_url": "https://api.github.com/users/justinmk/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/justinmk",
                "id": 1359421,
                "login": "justinmk",
                "node_id": "MDQ6VXNlcjEzNTk0MjE=",
                "organizations_url": "https://api.github.com/users/justinmk/orgs",
                "received_events_url": "https://api.github.com/users/justinmk/received_events",
                "repos_url": "https://api.github.com/users/justinmk/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/justinmk/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/justinmk/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/justinmk"
            }
        }
    ],
    "comments": 4,
    "comments_url": "https://api.github.com/repos/neovim/pynvim/issues/386/comments",
    "created_at": "2019-03-08T01:37:00Z",
    "events_url": "https://api.github.com/repos/neovim/pynvim/issues/386/events",
    "html_url": "https://github.com/neovim/pynvim/issues/386",
    "id": 418592695,
    "labels": [
        {
            "color": "f9d0c4",
            "default": true,
            "description": null,
            "id": 97892276,
            "name": "bug",
            "node_id": "MDU6TGFiZWw5Nzg5MjI3Ng==",
            "url": "https://api.github.com/repos/neovim/pynvim/labels/bug"
        }
    ],
    "labels_url": "https://api.github.com/repos/neovim/pynvim/issues/386/labels{/name}",
    "locked": false,
    "milestone": null,
    "node_id": "MDU6SXNzdWU0MTg1OTI2OTU=",
    "number": 386,
    "performed_via_github_app": null,
    "reactions": {
        "+1": 2,
        "-1": 0,
        "confused": 0,
        "eyes": 0,
        "heart": 0,
        "hooray": 0,
        "laugh": 0,
        "rocket": 0,
        "total_count": 2,
        "url": "https://api.github.com/repos/neovim/pynvim/issues/386/reactions"
    },
    "repository_url": "https://api.github.com/repos/neovim/pynvim",
    "state": "closed",
    "state_reason": "completed",
    "timeline_url": "https://api.github.com/repos/neovim/pynvim/issues/386/timeline",
    "title": "plugin.function is not being loaded in neovim",
    "updated_at": "2023-12-05T00:02:08Z",
    "url": "https://api.github.com/repos/neovim/pynvim/issues/386",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/1377268?v=4",
        "events_url": "https://api.github.com/users/punitsoni/events{/privacy}",
        "followers_url": "https://api.github.com/users/punitsoni/followers",
        "following_url": "https://api.github.com/users/punitsoni/following{/other_user}",
        "gists_url": "https://api.github.com/users/punitsoni/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/punitsoni",
        "id": 1377268,
        "login": "punitsoni",
        "node_id": "MDQ6VXNlcjEzNzcyNjg=",
        "organizations_url": "https://api.github.com/users/punitsoni/orgs",
        "received_events_url": "https://api.github.com/users/punitsoni/received_events",
        "repos_url": "https://api.github.com/users/punitsoni/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/punitsoni/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/punitsoni/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/punitsoni"
    }
}