{
    "active_lock_reason": null,
    "assignee": null,
    "assignees": [],
    "author_association": "NONE",
    "body": "```py\r\nTraceback (most recent call last):\r\n  File \"/usr/local/lib/python3.8/dist-packages/pynvim/plugin/host.py\", line 193, in _load\r\n    module = _handle_import(directory, name)\r\n  File \"/usr/local/lib/python3.8/dist-packages/pynvim/plugin/host.py\", line 40, in _handle_import\r\n    return importlib.import_module(name)\r\n  File \"/usr/lib/python3.8/importlib/__init__.py\", line 127, in import_module\r\n    return _bootstrap._gcd_import(name[level:], package, level)\r\n  File \"<frozen importlib._bootstrap>\", line 1014, in _gcd_import\r\n  File \"<frozen importlib._bootstrap>\", line 991, in _find_and_load\r\nTypeError: 'type' object is not subscriptable\r\n```\r\n\r\nReference: https://github.com/gptlang/CopilotChat.nvim/issues/18",
    "closed_at": "2024-01-30T07:37:41Z",
    "comment_data": [
        {
            "author_association": "MEMBER",
            "body": "https://github.com/neovim/pynvim/blob/5f989dfc47d98bba9f98e5ea17bfbe4c995cb0b0/pynvim/plugin/host.py#L40\r\n\r\nThat seems like a bug in `importlib`? Does it work on later python versions? ",
            "created_at": "2024-01-29T00:50:37Z",
            "html_url": "https://github.com/neovim/pynvim/issues/560#issuecomment-1913790086",
            "id": 1913790086,
            "issue_url": "https://api.github.com/repos/neovim/pynvim/issues/560",
            "node_id": "IC_kwDOASpKTs5yEh6G",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1913790086/reactions"
            },
            "updated_at": "2024-01-29T00:50:37Z",
            "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1913790086",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/1359421?v=4",
                "events_url": "https://api.github.com/users/justinmk/events{/privacy}",
                "followers_url": "https://api.github.com/users/justinmk/followers",
                "following_url": "https://api.github.com/users/justinmk/following{/other_user}",
                "gists_url": "https://api.github.com/users/justinmk/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/justinmk",
                "id": 1359421,
                "login": "justinmk",
                "node_id": "MDQ6VXNlcjEzNTk0MjE=",
                "organizations_url": "https://api.github.com/users/justinmk/orgs",
                "received_events_url": "https://api.github.com/users/justinmk/received_events",
                "repos_url": "https://api.github.com/users/justinmk/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/justinmk/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/justinmk/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/justinmk"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "> Traceback (most recent call last):\r\n>  File \"/usr/local/lib/python3.8/dist-packages/pynvim/plugin/host.py\", line 193, in _load\r\n>    module = _handle_import(directory, name)\r\n\r\nThat seems like an out of date package. Maybe there are changes on master that weren't release yet. Here's line 193:\r\n\r\nhttps://github.com/neovim/pynvim/blob/5f989dfc47d98bba9f98e5ea17bfbe4c995cb0b0/pynvim/plugin/host.py#L193",
            "created_at": "2024-01-29T00:53:01Z",
            "html_url": "https://github.com/neovim/pynvim/issues/560#issuecomment-1913791271",
            "id": 1913791271,
            "issue_url": "https://api.github.com/repos/neovim/pynvim/issues/560",
            "node_id": "IC_kwDOASpKTs5yEiMn",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1913791271/reactions"
            },
            "updated_at": "2024-01-29T00:53:01Z",
            "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1913791271",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/1359421?v=4",
                "events_url": "https://api.github.com/users/justinmk/events{/privacy}",
                "followers_url": "https://api.github.com/users/justinmk/followers",
                "following_url": "https://api.github.com/users/justinmk/following{/other_user}",
                "gists_url": "https://api.github.com/users/justinmk/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/justinmk",
                "id": 1359421,
                "login": "justinmk",
                "node_id": "MDQ6VXNlcjEzNTk0MjE=",
                "organizations_url": "https://api.github.com/users/justinmk/orgs",
                "received_events_url": "https://api.github.com/users/justinmk/received_events",
                "repos_url": "https://api.github.com/users/justinmk/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/justinmk/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/justinmk/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/justinmk"
            }
        },
        {
            "author_association": "NONE",
            "body": "> That seems like a bug in importlib? Does it work on later python versions?\r\n\r\nYes. Works on later versions. I'm pretty sure importlib is standard library though; it shouldn't be out of date",
            "created_at": "2024-01-29T07:08:57Z",
            "html_url": "https://github.com/neovim/pynvim/issues/560#issuecomment-1914086052",
            "id": 1914086052,
            "issue_url": "https://api.github.com/repos/neovim/pynvim/issues/560",
            "node_id": "IC_kwDOASpKTs5yFqKk",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1914086052/reactions"
            },
            "updated_at": "2024-01-29T07:10:36Z",
            "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1914086052",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/121417512?v=4",
                "events_url": "https://api.github.com/users/gptlang/events{/privacy}",
                "followers_url": "https://api.github.com/users/gptlang/followers",
                "following_url": "https://api.github.com/users/gptlang/following{/other_user}",
                "gists_url": "https://api.github.com/users/gptlang/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/gptlang",
                "id": 121417512,
                "login": "gptlang",
                "node_id": "U_kgDOBzyvKA",
                "organizations_url": "https://api.github.com/users/gptlang/orgs",
                "received_events_url": "https://api.github.com/users/gptlang/received_events",
                "repos_url": "https://api.github.com/users/gptlang/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/gptlang/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/gptlang/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/gptlang"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "I mean that your pynvim source is out of date compared to pynvim `master` (can you try that)?",
            "created_at": "2024-01-29T17:57:44Z",
            "html_url": "https://github.com/neovim/pynvim/issues/560#issuecomment-1915273249",
            "id": 1915273249,
            "issue_url": "https://api.github.com/repos/neovim/pynvim/issues/560",
            "node_id": "IC_kwDOASpKTs5yKMAh",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1915273249/reactions"
            },
            "updated_at": "2024-01-29T17:57:44Z",
            "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1915273249",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/1359421?v=4",
                "events_url": "https://api.github.com/users/justinmk/events{/privacy}",
                "followers_url": "https://api.github.com/users/justinmk/followers",
                "following_url": "https://api.github.com/users/justinmk/following{/other_user}",
                "gists_url": "https://api.github.com/users/justinmk/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/justinmk",
                "id": 1359421,
                "login": "justinmk",
                "node_id": "MDQ6VXNlcjEzNTk0MjE=",
                "organizations_url": "https://api.github.com/users/justinmk/orgs",
                "received_events_url": "https://api.github.com/users/justinmk/received_events",
                "repos_url": "https://api.github.com/users/justinmk/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/justinmk/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/justinmk/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/justinmk"
            }
        },
        {
            "author_association": "NONE",
            "body": "`pip install git+https://github.com/neovim/pynvim`?\r\n\r\nCC @Cassius0924 \r\n\r\nEdit: oops, wrong account",
            "created_at": "2024-01-30T05:39:04Z",
            "html_url": "https://github.com/neovim/pynvim/issues/560#issuecomment-1916114763",
            "id": 1916114763,
            "issue_url": "https://api.github.com/repos/neovim/pynvim/issues/560",
            "node_id": "IC_kwDOASpKTs5yNZdL",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1916114763/reactions"
            },
            "updated_at": "2024-01-30T07:07:49Z",
            "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1916114763",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/36258159?v=4",
                "events_url": "https://api.github.com/users/acheong08/events{/privacy}",
                "followers_url": "https://api.github.com/users/acheong08/followers",
                "following_url": "https://api.github.com/users/acheong08/following{/other_user}",
                "gists_url": "https://api.github.com/users/acheong08/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/acheong08",
                "id": 36258159,
                "login": "acheong08",
                "node_id": "MDQ6VXNlcjM2MjU4MTU5",
                "organizations_url": "https://api.github.com/users/acheong08/orgs",
                "received_events_url": "https://api.github.com/users/acheong08/received_events",
                "repos_url": "https://api.github.com/users/acheong08/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/acheong08/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/acheong08/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/acheong08"
            }
        },
        {
            "author_association": "NONE",
            "body": "> `git install git+https://github.com/neovim/pynvim`?\r\n> \r\n> CC @Cassius0924\r\n> \r\n> Edit: oops, wrong account\r\n\r\nIt seems like there's a small mistake in your command. It's `pip install` not `git install`.\r\n\r\nI used `pip install git+https://github.com/neovim/pynvim` to upgrade the pynvim version to 0.5.0.dev0, but there are still errors, but the error line has changed from `line 193` to `line 187`\r\n\r\n```\r\nEncountered TypeError loading plugin at /root/.local/share/lunarvim/site/pack/lazy/opt/CopilotChat.nvim/rplugin/python3/utilities.py: 'type' object is not subscriptable\r\nTraceback (most recent call last):\r\n  File \"/usr/local/lib/python3.8/dist-packages/pynvim/plugin/host.py\", line 187, in _load\r\n    module = _handle_import(directory, name)\r\n  File \"/usr/local/lib/python3.8/dist-packages/pynvim/plugin/host.py\", line 40, in _handle_import\r\n    return importlib.import_module(name)\r\n  File \"/usr/lib/python3.8/importlib/__init__.py\", line 127, in import_module\r\n    return _bootstrap._gcd_import(name[level:], package, level)\r\n  File \"<frozen importlib._bootstrap>\", line 1014, in _gcd_import\r\n  File \"<frozen importlib._bootstrap>\", line 991, in _find_and_load\r\nTypeError: 'type' object is not subscriptable\r\n\r\nremote/host: python3 host registered plugins []\r\nremote/host: generated rplugin manifest: /root/.local/share/lvim/rplugin.vim\r\n```\r\n",
            "created_at": "2024-01-30T07:05:48Z",
            "html_url": "https://github.com/neovim/pynvim/issues/560#issuecomment-1916200135",
            "id": 1916200135,
            "issue_url": "https://api.github.com/repos/neovim/pynvim/issues/560",
            "node_id": "IC_kwDOASpKTs5yNuTH",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1916200135/reactions"
            },
            "updated_at": "2024-01-30T07:05:48Z",
            "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1916200135",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/62874592?v=4",
                "events_url": "https://api.github.com/users/Cassius0924/events{/privacy}",
                "followers_url": "https://api.github.com/users/Cassius0924/followers",
                "following_url": "https://api.github.com/users/Cassius0924/following{/other_user}",
                "gists_url": "https://api.github.com/users/Cassius0924/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/Cassius0924",
                "id": 62874592,
                "login": "Cassius0924",
                "node_id": "MDQ6VXNlcjYyODc0NTky",
                "organizations_url": "https://api.github.com/users/Cassius0924/orgs",
                "received_events_url": "https://api.github.com/users/Cassius0924/received_events",
                "repos_url": "https://api.github.com/users/Cassius0924/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/Cassius0924/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/Cassius0924/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/Cassius0924"
            }
        },
        {
            "author_association": "NONE",
            "body": "> It seems like there's a small mistake in your command. It's pip install not git install.\r\n\r\nYup. Typo\r\n\r\nCould you try to reproduce this with a minimal Python file by importing `importlib` and calling it?",
            "created_at": "2024-01-30T07:08:14Z",
            "html_url": "https://github.com/neovim/pynvim/issues/560#issuecomment-1916203244",
            "id": 1916203244,
            "issue_url": "https://api.github.com/repos/neovim/pynvim/issues/560",
            "node_id": "IC_kwDOASpKTs5yNvDs",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1916203244/reactions"
            },
            "updated_at": "2024-01-30T07:08:42Z",
            "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1916203244",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/36258159?v=4",
                "events_url": "https://api.github.com/users/acheong08/events{/privacy}",
                "followers_url": "https://api.github.com/users/acheong08/followers",
                "following_url": "https://api.github.com/users/acheong08/following{/other_user}",
                "gists_url": "https://api.github.com/users/acheong08/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/acheong08",
                "id": 36258159,
                "login": "acheong08",
                "node_id": "MDQ6VXNlcjM2MjU4MTU5",
                "organizations_url": "https://api.github.com/users/acheong08/orgs",
                "received_events_url": "https://api.github.com/users/acheong08/received_events",
                "repos_url": "https://api.github.com/users/acheong08/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/acheong08/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/acheong08/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/acheong08"
            }
        },
        {
            "author_association": "NONE",
            "body": "Like below?\r\n\r\nI wrote a Python file:\r\n\r\n```python\r\nimport importlib\r\nimport sys\r\n\r\nsys.path.append(\r\n    \"/root/.local/share/lunarvim/site/pack/lazy/opt/CopilotChat.nvim/rplugin/python3\"\r\n)\r\n\r\n\r\ndef test_import(name):\r\n    importlib.import_module(name)\r\n\r\n\r\ntest_import(\"copilot\")\r\n```\r\n\r\nStill getting error after running: \r\n\r\n```\r\nTraceback (most recent call last):\r\n  File \"t_1.py\", line 17, in <module>\r\n    test_import(\"copilot\")\r\n  File \"t_1.py\", line 11, in test_import\r\n    importlib.import_module(name)\r\n  File \"/usr/lib/python3.8/importlib/__init__.py\", line 127, in import_module\r\n    return _bootstrap._gcd_import(name[level:], package, level)\r\n  File \"<frozen importlib._bootstrap>\", line 1014, in _gcd_import\r\n  File \"<frozen importlib._bootstrap>\", line 991, in _find_and_load\r\n  File \"<frozen importlib._bootstrap>\", line 975, in _find_and_load_unlocked\r\n  File \"<frozen importlib._bootstrap>\", line 671, in _load_unlocked\r\n  File \"<frozen importlib._bootstrap_external>\", line 848, in exec_module\r\n  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\r\n  File \"/root/.local/share/lunarvim/site/pack/lazy/opt/CopilotChat.nvim/rplugin/python3/copilot.py\", line 10, in <module>\r\n    import utilities\r\n  File \"/root/.local/share/lunarvim/site/pack/lazy/opt/CopilotChat.nvim/rplugin/python3/utilities.py\", line 13, in <module>\r\n    chat_history: list[typings.Message],\r\nTypeError: 'type' object is not subscriptable\r\n```",
            "created_at": "2024-01-30T07:23:32Z",
            "html_url": "https://github.com/neovim/pynvim/issues/560#issuecomment-1916222720",
            "id": 1916222720,
            "issue_url": "https://api.github.com/repos/neovim/pynvim/issues/560",
            "node_id": "IC_kwDOASpKTs5yNz0A",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1916222720/reactions"
            },
            "updated_at": "2024-01-30T07:23:32Z",
            "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1916222720",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/62874592?v=4",
                "events_url": "https://api.github.com/users/Cassius0924/events{/privacy}",
                "followers_url": "https://api.github.com/users/Cassius0924/followers",
                "following_url": "https://api.github.com/users/Cassius0924/following{/other_user}",
                "gists_url": "https://api.github.com/users/Cassius0924/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/Cassius0924",
                "id": 62874592,
                "login": "Cassius0924",
                "node_id": "MDQ6VXNlcjYyODc0NTky",
                "organizations_url": "https://api.github.com/users/Cassius0924/orgs",
                "received_events_url": "https://api.github.com/users/Cassius0924/received_events",
                "repos_url": "https://api.github.com/users/Cassius0924/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/Cassius0924/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/Cassius0924/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/Cassius0924"
            }
        },
        {
            "author_association": "NONE",
            "body": "This error seems not to be from pynvim, but from CopilotChat. I tried replacing `list` with `List` and it worked normally.",
            "created_at": "2024-01-30T07:34:06Z",
            "html_url": "https://github.com/neovim/pynvim/issues/560#issuecomment-1916235167",
            "id": 1916235167,
            "issue_url": "https://api.github.com/repos/neovim/pynvim/issues/560",
            "node_id": "IC_kwDOASpKTs5yN22f",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1916235167/reactions"
            },
            "updated_at": "2024-01-30T07:34:06Z",
            "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1916235167",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/62874592?v=4",
                "events_url": "https://api.github.com/users/Cassius0924/events{/privacy}",
                "followers_url": "https://api.github.com/users/Cassius0924/followers",
                "following_url": "https://api.github.com/users/Cassius0924/following{/other_user}",
                "gists_url": "https://api.github.com/users/Cassius0924/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/Cassius0924",
                "id": 62874592,
                "login": "Cassius0924",
                "node_id": "MDQ6VXNlcjYyODc0NTky",
                "organizations_url": "https://api.github.com/users/Cassius0924/orgs",
                "received_events_url": "https://api.github.com/users/Cassius0924/received_events",
                "repos_url": "https://api.github.com/users/Cassius0924/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/Cassius0924/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/Cassius0924/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/Cassius0924"
            }
        },
        {
            "author_association": "NONE",
            "body": "Ah I see. I suppose I got confused by the error output",
            "created_at": "2024-01-30T07:37:01Z",
            "html_url": "https://github.com/neovim/pynvim/issues/560#issuecomment-1916238613",
            "id": 1916238613,
            "issue_url": "https://api.github.com/repos/neovim/pynvim/issues/560",
            "node_id": "IC_kwDOASpKTs5yN3sV",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1916238613/reactions"
            },
            "updated_at": "2024-01-30T07:37:01Z",
            "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1916238613",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/121417512?v=4",
                "events_url": "https://api.github.com/users/gptlang/events{/privacy}",
                "followers_url": "https://api.github.com/users/gptlang/followers",
                "following_url": "https://api.github.com/users/gptlang/following{/other_user}",
                "gists_url": "https://api.github.com/users/gptlang/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/gptlang",
                "id": 121417512,
                "login": "gptlang",
                "node_id": "U_kgDOBzyvKA",
                "organizations_url": "https://api.github.com/users/gptlang/orgs",
                "received_events_url": "https://api.github.com/users/gptlang/received_events",
                "repos_url": "https://api.github.com/users/gptlang/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/gptlang/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/gptlang/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/gptlang"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "Yes, the error was coming from the rplugin code, but the error message printed in Nvim can be confusing. We can improve error messages to clearly indicate that the SyntaxError/RuntimeError originates from the remote plugin.",
            "created_at": "2024-02-04T06:55:44Z",
            "html_url": "https://github.com/neovim/pynvim/issues/560#issuecomment-1925603303",
            "id": 1925603303,
            "issue_url": "https://api.github.com/repos/neovim/pynvim/issues/560",
            "node_id": "IC_kwDOASpKTs5yxl_n",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 1,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 1,
                "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1925603303/reactions"
            },
            "updated_at": "2024-02-04T06:55:44Z",
            "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1925603303",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/1009873?v=4",
                "events_url": "https://api.github.com/users/wookayin/events{/privacy}",
                "followers_url": "https://api.github.com/users/wookayin/followers",
                "following_url": "https://api.github.com/users/wookayin/following{/other_user}",
                "gists_url": "https://api.github.com/users/wookayin/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/wookayin",
                "id": 1009873,
                "login": "wookayin",
                "node_id": "MDQ6VXNlcjEwMDk4NzM=",
                "organizations_url": "https://api.github.com/users/wookayin/orgs",
                "received_events_url": "https://api.github.com/users/wookayin/received_events",
                "repos_url": "https://api.github.com/users/wookayin/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/wookayin/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/wookayin/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/wookayin"
            }
        }
    ],
    "comments": 11,
    "comments_url": "https://api.github.com/repos/neovim/pynvim/issues/560/comments",
    "created_at": "2024-01-28T04:54:29Z",
    "events_url": "https://api.github.com/repos/neovim/pynvim/issues/560/events",
    "html_url": "https://github.com/neovim/pynvim/issues/560",
    "id": 2103968788,
    "labels": [
        {
            "color": "e6e6e6",
            "default": true,
            "description": "",
            "id": 97892281,
            "name": "question",
            "node_id": "MDU6TGFiZWw5Nzg5MjI4MQ==",
            "url": "https://api.github.com/repos/neovim/pynvim/labels/question"
        }
    ],
    "labels_url": "https://api.github.com/repos/neovim/pynvim/issues/560/labels{/name}",
    "locked": false,
    "milestone": null,
    "node_id": "I_kwDOASpKTs59aAQU",
    "number": 560,
    "performed_via_github_app": null,
    "reactions": {
        "+1": 0,
        "-1": 0,
        "confused": 0,
        "eyes": 0,
        "heart": 0,
        "hooray": 0,
        "laugh": 0,
        "rocket": 0,
        "total_count": 0,
        "url": "https://api.github.com/repos/neovim/pynvim/issues/560/reactions"
    },
    "repository_url": "https://api.github.com/repos/neovim/pynvim",
    "state": "closed",
    "state_reason": "not_planned",
    "timeline_url": "https://api.github.com/repos/neovim/pynvim/issues/560/timeline",
    "title": "Python 3.8: TypeError: 'type' object is not subscriptable",
    "updated_at": "2024-02-04T06:55:44Z",
    "url": "https://api.github.com/repos/neovim/pynvim/issues/560",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/121417512?v=4",
        "events_url": "https://api.github.com/users/gptlang/events{/privacy}",
        "followers_url": "https://api.github.com/users/gptlang/followers",
        "following_url": "https://api.github.com/users/gptlang/following{/other_user}",
        "gists_url": "https://api.github.com/users/gptlang/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/gptlang",
        "id": 121417512,
        "login": "gptlang",
        "node_id": "U_kgDOBzyvKA",
        "organizations_url": "https://api.github.com/users/gptlang/orgs",
        "received_events_url": "https://api.github.com/users/gptlang/received_events",
        "repos_url": "https://api.github.com/users/gptlang/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/gptlang/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/gptlang/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/gptlang"
    }
}