{
    "active_lock_reason": null,
    "assignee": null,
    "assignees": [],
    "author_association": "NONE",
    "body": "```py\r\nTraceback (most recent call last):\r\n  File \"/usr/local/lib/python3.8/dist-packages/pynvim/plugin/host.py\", line 193, in _load\r\n    module = _handle_import(directory, name)\r\n  File \"/usr/local/lib/python3.8/dist-packages/pynvim/plugin/host.py\", line 40, in _handle_import\r\n    return importlib.import_module(name)\r\n  File \"/usr/lib/python3.8/importlib/__init__.py\", line 127, in import_module\r\n    return _bootstrap._gcd_import(name[level:], package, level)\r\n  File \"<frozen importlib._bootstrap>\", line 1014, in _gcd_import\r\n  File \"<frozen importlib._bootstrap>\", line 991, in _find_and_load\r\nTypeError: 'type' object is not subscriptable\r\n```\r\n\r\nReference: https://github.com/gptlang/CopilotChat.nvim/issues/18",
    "closed_at": null,
    "comment_data": [
        {
            "author_association": "MEMBER",
            "body": "https://github.com/neovim/pynvim/blob/5f989dfc47d98bba9f98e5ea17bfbe4c995cb0b0/pynvim/plugin/host.py#L40\r\n\r\nThat seems like a bug in `importlib`? Does it work on later python versions? ",
            "created_at": "2024-01-29T00:50:37Z",
            "html_url": "https://github.com/neovim/pynvim/issues/560#issuecomment-1913790086",
            "id": 1913790086,
            "issue_url": "https://api.github.com/repos/neovim/pynvim/issues/560",
            "node_id": "IC_kwDOASpKTs5yEh6G",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1913790086/reactions"
            },
            "updated_at": "2024-01-29T00:50:37Z",
            "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1913790086",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/1359421?v=4",
                "events_url": "https://api.github.com/users/justinmk/events{/privacy}",
                "followers_url": "https://api.github.com/users/justinmk/followers",
                "following_url": "https://api.github.com/users/justinmk/following{/other_user}",
                "gists_url": "https://api.github.com/users/justinmk/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/justinmk",
                "id": 1359421,
                "login": "justinmk",
                "node_id": "MDQ6VXNlcjEzNTk0MjE=",
                "organizations_url": "https://api.github.com/users/justinmk/orgs",
                "received_events_url": "https://api.github.com/users/justinmk/received_events",
                "repos_url": "https://api.github.com/users/justinmk/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/justinmk/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/justinmk/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/justinmk"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "> Traceback (most recent call last):\r\n>  File \"/usr/local/lib/python3.8/dist-packages/pynvim/plugin/host.py\", line 193, in _load\r\n>    module = _handle_import(directory, name)\r\n\r\nThat seems like an out of date package. Maybe there are changes on master that weren't release yet. Here's line 193:\r\n\r\nhttps://github.com/neovim/pynvim/blob/5f989dfc47d98bba9f98e5ea17bfbe4c995cb0b0/pynvim/plugin/host.py#L193",
            "created_at": "2024-01-29T00:53:01Z",
            "html_url": "https://github.com/neovim/pynvim/issues/560#issuecomment-1913791271",
            "id": 1913791271,
            "issue_url": "https://api.github.com/repos/neovim/pynvim/issues/560",
            "node_id": "IC_kwDOASpKTs5yEiMn",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1913791271/reactions"
            },
            "updated_at": "2024-01-29T00:53:01Z",
            "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1913791271",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/1359421?v=4",
                "events_url": "https://api.github.com/users/justinmk/events{/privacy}",
                "followers_url": "https://api.github.com/users/justinmk/followers",
                "following_url": "https://api.github.com/users/justinmk/following{/other_user}",
                "gists_url": "https://api.github.com/users/justinmk/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/justinmk",
                "id": 1359421,
                "login": "justinmk",
                "node_id": "MDQ6VXNlcjEzNTk0MjE=",
                "organizations_url": "https://api.github.com/users/justinmk/orgs",
                "received_events_url": "https://api.github.com/users/justinmk/received_events",
                "repos_url": "https://api.github.com/users/justinmk/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/justinmk/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/justinmk/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/justinmk"
            }
        },
        {
            "author_association": "NONE",
            "body": "> That seems like a bug in importlib? Does it work on later python versions?\r\n\r\nYes. Works on later versions. I'm pretty sure importlib is standard library though; it shouldn't be out of date",
            "created_at": "2024-01-29T07:08:57Z",
            "html_url": "https://github.com/neovim/pynvim/issues/560#issuecomment-1914086052",
            "id": 1914086052,
            "issue_url": "https://api.github.com/repos/neovim/pynvim/issues/560",
            "node_id": "IC_kwDOASpKTs5yFqKk",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1914086052/reactions"
            },
            "updated_at": "2024-01-29T07:10:36Z",
            "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1914086052",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/121417512?v=4",
                "events_url": "https://api.github.com/users/gptlang/events{/privacy}",
                "followers_url": "https://api.github.com/users/gptlang/followers",
                "following_url": "https://api.github.com/users/gptlang/following{/other_user}",
                "gists_url": "https://api.github.com/users/gptlang/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/gptlang",
                "id": 121417512,
                "login": "gptlang",
                "node_id": "U_kgDOBzyvKA",
                "organizations_url": "https://api.github.com/users/gptlang/orgs",
                "received_events_url": "https://api.github.com/users/gptlang/received_events",
                "repos_url": "https://api.github.com/users/gptlang/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/gptlang/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/gptlang/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/gptlang"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "I mean that your pynvim source is out of date compared to pynvim `master` (can you try that)?",
            "created_at": "2024-01-29T17:57:44Z",
            "html_url": "https://github.com/neovim/pynvim/issues/560#issuecomment-1915273249",
            "id": 1915273249,
            "issue_url": "https://api.github.com/repos/neovim/pynvim/issues/560",
            "node_id": "IC_kwDOASpKTs5yKMAh",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1915273249/reactions"
            },
            "updated_at": "2024-01-29T17:57:44Z",
            "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/1915273249",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/1359421?v=4",
                "events_url": "https://api.github.com/users/justinmk/events{/privacy}",
                "followers_url": "https://api.github.com/users/justinmk/followers",
                "following_url": "https://api.github.com/users/justinmk/following{/other_user}",
                "gists_url": "https://api.github.com/users/justinmk/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/justinmk",
                "id": 1359421,
                "login": "justinmk",
                "node_id": "MDQ6VXNlcjEzNTk0MjE=",
                "organizations_url": "https://api.github.com/users/justinmk/orgs",
                "received_events_url": "https://api.github.com/users/justinmk/received_events",
                "repos_url": "https://api.github.com/users/justinmk/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/justinmk/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/justinmk/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/justinmk"
            }
        }
    ],
    "comments": 4,
    "comments_url": "https://api.github.com/repos/neovim/pynvim/issues/560/comments",
    "created_at": "2024-01-28T04:54:29Z",
    "events_url": "https://api.github.com/repos/neovim/pynvim/issues/560/events",
    "html_url": "https://github.com/neovim/pynvim/issues/560",
    "id": 2103968788,
    "labels": [
        {
            "color": "f9d0c4",
            "default": true,
            "description": null,
            "id": 97892276,
            "name": "bug",
            "node_id": "MDU6TGFiZWw5Nzg5MjI3Ng==",
            "url": "https://api.github.com/repos/neovim/pynvim/labels/bug"
        }
    ],
    "labels_url": "https://api.github.com/repos/neovim/pynvim/issues/560/labels{/name}",
    "locked": false,
    "milestone": null,
    "node_id": "I_kwDOASpKTs59aAQU",
    "number": 560,
    "performed_via_github_app": null,
    "reactions": {
        "+1": 0,
        "-1": 0,
        "confused": 0,
        "eyes": 0,
        "heart": 0,
        "hooray": 0,
        "laugh": 0,
        "rocket": 0,
        "total_count": 0,
        "url": "https://api.github.com/repos/neovim/pynvim/issues/560/reactions"
    },
    "repository_url": "https://api.github.com/repos/neovim/pynvim",
    "state": "open",
    "state_reason": null,
    "timeline_url": "https://api.github.com/repos/neovim/pynvim/issues/560/timeline",
    "title": "Python 3.8: TypeError: 'type' object is not subscriptable",
    "updated_at": "2024-01-29T17:57:54Z",
    "url": "https://api.github.com/repos/neovim/pynvim/issues/560",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/121417512?v=4",
        "events_url": "https://api.github.com/users/gptlang/events{/privacy}",
        "followers_url": "https://api.github.com/users/gptlang/followers",
        "following_url": "https://api.github.com/users/gptlang/following{/other_user}",
        "gists_url": "https://api.github.com/users/gptlang/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/gptlang",
        "id": 121417512,
        "login": "gptlang",
        "node_id": "U_kgDOBzyvKA",
        "organizations_url": "https://api.github.com/users/gptlang/orgs",
        "received_events_url": "https://api.github.com/users/gptlang/received_events",
        "repos_url": "https://api.github.com/users/gptlang/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/gptlang/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/gptlang/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/gptlang"
    }
}