{
    "active_lock_reason": null,
    "assignee": null,
    "assignees": [],
    "author_association": "NONE",
    "body": "Fresh-installing pynvim on a new environment will fail to import the module due to the lack of `typing_extensions` (at least in Python 3.9). Thus the package should be listed as a dependency, maybe depending on the python version.",
    "closed_at": "2024-11-11T06:36:11Z",
    "closed_by": {
        "avatar_url": "https://avatars.githubusercontent.com/u/12980409?v=4",
        "events_url": "https://api.github.com/users/kiyoon/events{/privacy}",
        "followers_url": "https://api.github.com/users/kiyoon/followers",
        "following_url": "https://api.github.com/users/kiyoon/following{/other_user}",
        "gists_url": "https://api.github.com/users/kiyoon/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/kiyoon",
        "id": 12980409,
        "login": "kiyoon",
        "node_id": "MDQ6VXNlcjEyOTgwNDA5",
        "organizations_url": "https://api.github.com/users/kiyoon/orgs",
        "received_events_url": "https://api.github.com/users/kiyoon/received_events",
        "repos_url": "https://api.github.com/users/kiyoon/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/kiyoon/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/kiyoon/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/kiyoon",
        "user_view_type": "public"
    },
    "comment_data": [
        {
            "author_association": "NONE",
            "body": "I think it's already addressed in the master branch, but maybe not the pypi version 0.5.1. Sorry! Closing as completed",
            "created_at": "2024-11-11T06:36:11Z",
            "html_url": "https://github.com/neovim/pynvim/issues/582#issuecomment-2467351521",
            "id": 2467351521,
            "issue_url": "https://api.github.com/repos/neovim/pynvim/issues/582",
            "node_id": "IC_kwDOASpKTs6TEMvh",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/2467351521/reactions"
            },
            "updated_at": "2024-11-11T06:36:11Z",
            "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/2467351521",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/12980409?v=4",
                "events_url": "https://api.github.com/users/kiyoon/events{/privacy}",
                "followers_url": "https://api.github.com/users/kiyoon/followers",
                "following_url": "https://api.github.com/users/kiyoon/following{/other_user}",
                "gists_url": "https://api.github.com/users/kiyoon/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/kiyoon",
                "id": 12980409,
                "login": "kiyoon",
                "node_id": "MDQ6VXNlcjEyOTgwNDA5",
                "organizations_url": "https://api.github.com/users/kiyoon/orgs",
                "received_events_url": "https://api.github.com/users/kiyoon/received_events",
                "repos_url": "https://api.github.com/users/kiyoon/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/kiyoon/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/kiyoon/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/kiyoon",
                "user_view_type": "public"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "While I can see that this has been fixed in #581, I don't see why [CI](https://github.com/neovim/pynvim/blob/master/.github/workflows/test.yml) hadn't been unable to catch this (before #581 was merged).\n\nEDIT: I got it, the following is still executed during `pip install -e.`, but this dependency is not published to PyPI as the release was made with python >= 3.12. We should make a new release anyway; thanks for reporting.\n```\nif sys.version_info < (3, 12):\n    install_requires.append('typing-extensions>=4.5')\n```",
            "created_at": "2024-11-12T14:37:16Z",
            "html_url": "https://github.com/neovim/pynvim/issues/582#issuecomment-2470708148",
            "id": 2470708148,
            "issue_url": "https://api.github.com/repos/neovim/pynvim/issues/582",
            "node_id": "IC_kwDOASpKTs6TRAO0",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/2470708148/reactions"
            },
            "updated_at": "2024-11-13T02:45:27Z",
            "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/2470708148",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/1009873?v=4",
                "events_url": "https://api.github.com/users/wookayin/events{/privacy}",
                "followers_url": "https://api.github.com/users/wookayin/followers",
                "following_url": "https://api.github.com/users/wookayin/following{/other_user}",
                "gists_url": "https://api.github.com/users/wookayin/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/wookayin",
                "id": 1009873,
                "login": "wookayin",
                "node_id": "MDQ6VXNlcjEwMDk4NzM=",
                "organizations_url": "https://api.github.com/users/wookayin/orgs",
                "received_events_url": "https://api.github.com/users/wookayin/received_events",
                "repos_url": "https://api.github.com/users/wookayin/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/wookayin/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/wookayin/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/wookayin",
                "user_view_type": "public"
            }
        },
        {
            "author_association": "NONE",
            "body": "@wookayin ahh that makes sense. Very interesting bug! Thanks for investigating :)) ",
            "created_at": "2024-11-12T15:49:01Z",
            "html_url": "https://github.com/neovim/pynvim/issues/582#issuecomment-2470892650",
            "id": 2470892650,
            "issue_url": "https://api.github.com/repos/neovim/pynvim/issues/582",
            "node_id": "IC_kwDOASpKTs6TRtRq",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/2470892650/reactions"
            },
            "updated_at": "2024-11-12T15:49:01Z",
            "url": "https://api.github.com/repos/neovim/pynvim/issues/comments/2470892650",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/12980409?v=4",
                "events_url": "https://api.github.com/users/kiyoon/events{/privacy}",
                "followers_url": "https://api.github.com/users/kiyoon/followers",
                "following_url": "https://api.github.com/users/kiyoon/following{/other_user}",
                "gists_url": "https://api.github.com/users/kiyoon/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/kiyoon",
                "id": 12980409,
                "login": "kiyoon",
                "node_id": "MDQ6VXNlcjEyOTgwNDA5",
                "organizations_url": "https://api.github.com/users/kiyoon/orgs",
                "received_events_url": "https://api.github.com/users/kiyoon/received_events",
                "repos_url": "https://api.github.com/users/kiyoon/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/kiyoon/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/kiyoon/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/kiyoon",
                "user_view_type": "public"
            }
        }
    ],
    "comments": 3,
    "comments_url": "https://api.github.com/repos/neovim/pynvim/issues/582/comments",
    "created_at": "2024-11-11T06:30:20Z",
    "events_url": "https://api.github.com/repos/neovim/pynvim/issues/582/events",
    "html_url": "https://github.com/neovim/pynvim/issues/582",
    "id": 2648307780,
    "labels": [
        {
            "color": "f9d0c4",
            "default": true,
            "description": null,
            "id": 97892276,
            "name": "bug",
            "node_id": "MDU6TGFiZWw5Nzg5MjI3Ng==",
            "url": "https://api.github.com/repos/neovim/pynvim/labels/bug"
        }
    ],
    "labels_url": "https://api.github.com/repos/neovim/pynvim/issues/582/labels{/name}",
    "locked": false,
    "milestone": null,
    "node_id": "I_kwDOASpKTs6d2fhE",
    "number": 582,
    "performed_via_github_app": null,
    "reactions": {
        "+1": 0,
        "-1": 0,
        "confused": 0,
        "eyes": 0,
        "heart": 0,
        "hooray": 0,
        "laugh": 0,
        "rocket": 0,
        "total_count": 0,
        "url": "https://api.github.com/repos/neovim/pynvim/issues/582/reactions"
    },
    "repository_url": "https://api.github.com/repos/neovim/pynvim",
    "state": "closed",
    "state_reason": "completed",
    "sub_issues_summary": {
        "completed": 0,
        "percent_completed": 0,
        "total": 0
    },
    "timeline_url": "https://api.github.com/repos/neovim/pynvim/issues/582/timeline",
    "title": "typing_extensions should be a dependency",
    "updated_at": "2024-11-13T02:45:27Z",
    "url": "https://api.github.com/repos/neovim/pynvim/issues/582",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/12980409?v=4",
        "events_url": "https://api.github.com/users/kiyoon/events{/privacy}",
        "followers_url": "https://api.github.com/users/kiyoon/followers",
        "following_url": "https://api.github.com/users/kiyoon/following{/other_user}",
        "gists_url": "https://api.github.com/users/kiyoon/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/kiyoon",
        "id": 12980409,
        "login": "kiyoon",
        "node_id": "MDQ6VXNlcjEyOTgwNDA5",
        "organizations_url": "https://api.github.com/users/kiyoon/orgs",
        "received_events_url": "https://api.github.com/users/kiyoon/received_events",
        "repos_url": "https://api.github.com/users/kiyoon/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/kiyoon/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/kiyoon/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/kiyoon",
        "user_view_type": "public"
    }
}